"""Initial migration.

Revision ID: 5771b8c52a9d
Revises: 
Create Date: 2021-02-14 21:49:15.147030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5771b8c52a9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rent_price', sa.Integer(), nullable=True),
    sa.Column('name_auto', sa.String(length=128), nullable=True),
    sa.Column('img_url', sa.String(length=128), nullable=True),
    sa.Column('rent', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('availability', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
