"""Initial migration.

Revision ID: 6ae03b926ff1
Revises: 
Create Date: 2021-02-21 17:20:33.060843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae03b926ff1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rent_price', sa.Integer(), nullable=True),
    sa.Column('name_auto', sa.String(length=128), nullable=True),
    sa.Column('img_url', sa.String(length=128), nullable=True),
    sa.Column('img_url2', sa.String(length=128), nullable=True),
    sa.Column('img_url3', sa.String(length=128), nullable=True),
    sa.Column('img_url4', sa.String(length=128), nullable=True),
    sa.Column('transmission', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('num_book', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.Column('total_rent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_info', sa.Integer(), nullable=True),
    sa.Column('time_begin', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auto_info'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal')
    op.drop_table('car')
    # ### end Alembic commands ###
